/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicConnexionRouteImport } from './routes/_public/connexion'
import { Route as PublicLocationMaterielChar123villeChar125RouteImport } from './routes/_public/location-materiel-{$ville}'
import { Route as PublicMonCompteRouteImport } from './routes/_public/mon-compte'
import { Route as PublicPanierRouteImport } from './routes/_public/panier'
import { Route as PublicReservationRouteImport } from './routes/_public/reservation'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMotDePasseOublieRouteImport } from './routes/admin/mot-de-passe-oublie'
import { Route as AdminReinitialiserMotDePasseRouteImport } from './routes/admin/reinitialiser-mot-de-passe'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as PublicReservationReferenceRouteImport } from './routes/_public/reservation/$reference'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutCompteRouteImport } from './routes/admin/_layout/compte'
import { Route as AdminLayoutDureesRouteImport } from './routes/admin/_layout/durees'
import { Route as AdminLayoutEquipementsRouteImport } from './routes/admin/_layout/equipements'
import { Route as AdminLayoutFacturationRouteImport } from './routes/admin/_layout/facturation'
import { Route as AdminLayoutReglagesRouteImport } from './routes/admin/_layout/reglages'
import { Route as AdminLayoutReservationsRouteImport } from './routes/admin/_layout/reservations'
import { Route as AdminLayoutStatistiquesRouteImport } from './routes/admin/_layout/statistiques'
import { Route as AdminLayoutUtilisateursRouteImport } from './routes/admin/_layout/utilisateurs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicActiviteActivitySlugIndexRouteImport } from './routes/_public/activite/$activitySlug/index'
import { Route as PublicActiviteActivitySlugProductSlugRouteImport } from './routes/_public/activite/$activitySlug/$productSlug'
import { Route as AdminLayoutEquipeIndexRouteImport } from './routes/admin/_layout/equipe/index'
import { Route as AdminLayoutEquipementsIndexRouteImport } from './routes/admin/_layout/equipements/index'
import { Route as AdminLayoutEquipementsItemIdRouteImport } from './routes/admin/_layout/equipements/$itemId'
import { Route as AdminLayoutEquipementsAjouterRouteImport } from './routes/admin/_layout/equipements/ajouter'
import { Route as AdminLayoutReglagesIndexRouteImport } from './routes/admin/_layout/reglages/index'
import { Route as AdminLayoutReglagesCategoriesRouteImport } from './routes/admin/_layout/reglages/categories'
import { Route as AdminLayoutReglagesFacturationRouteImport } from './routes/admin/_layout/reglages/facturation'
import { Route as AdminLayoutReglagesHorairesRouteImport } from './routes/admin/_layout/reglages/horaires'
import { Route as AdminLayoutReglagesProduitsRouteImport } from './routes/admin/_layout/reglages/produits'
import { Route as AdminLayoutReservationsIndexRouteImport } from './routes/admin/_layout/reservations/index'
import { Route as AdminLayoutReservationsReservationIdRouteImport } from './routes/admin/_layout/reservations/$reservationId'
import { Route as AdminLayoutReservationsAjouterRouteImport } from './routes/admin/_layout/reservations/ajouter'
import { Route as AdminLayoutUtilisateursIndexRouteImport } from './routes/admin/_layout/utilisateurs/index'
import { Route as AdminLayoutUtilisateursUserIdRouteImport } from './routes/admin/_layout/utilisateurs/$userId'
import { Route as AdminLayoutUtilisateursAjouterRouteImport } from './routes/admin/_layout/utilisateurs/ajouter'
import { Route as AdminLayoutEquipementsItemIdIndexRouteImport } from './routes/admin/_layout/equipements/$itemId/index'
import { Route as AdminLayoutEquipementsItemIdModifierRouteImport } from './routes/admin/_layout/equipements/$itemId/modifier'
import { Route as AdminLayoutReservationsReservationIdIndexRouteImport } from './routes/admin/_layout/reservations/$reservationId/index'
import { Route as AdminLayoutUtilisateursUserIdIndexRouteImport } from './routes/admin/_layout/utilisateurs/$userId/index'
import { Route as AdminLayoutUtilisateursUserIdModifierRouteImport } from './routes/admin/_layout/utilisateurs/$userId/modifier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicConnexionRoute = PublicConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLocationMaterielChar123villeChar125Route =
  PublicLocationMaterielChar123villeChar125RouteImport.update({
    id: '/location-materiel-{$ville}',
    path: '/location-materiel-{$ville}',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicMonCompteRoute = PublicMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPanierRoute = PublicPanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReservationRoute = PublicReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => PublicRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMotDePasseOublieRoute = AdminMotDePasseOublieRouteImport.update({
  id: '/admin/mot-de-passe-oublie',
  path: '/admin/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReinitialiserMotDePasseRoute =
  AdminReinitialiserMotDePasseRouteImport.update({
    id: '/admin/reinitialiser-mot-de-passe',
    path: '/admin/reinitialiser-mot-de-passe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicReservationReferenceRoute =
  PublicReservationReferenceRouteImport.update({
    id: '/$reference',
    path: '/$reference',
    getParentRoute: () => PublicReservationRoute,
  } as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCompteRoute = AdminLayoutCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDureesRoute = AdminLayoutDureesRouteImport.update({
  id: '/durees',
  path: '/durees',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutEquipementsRoute = AdminLayoutEquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutFacturationRoute = AdminLayoutFacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutReglagesRoute = AdminLayoutReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutReservationsRoute = AdminLayoutReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutStatistiquesRoute = AdminLayoutStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutUtilisateursRoute = AdminLayoutUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicActiviteActivitySlugIndexRoute =
  PublicActiviteActivitySlugIndexRouteImport.update({
    id: '/activite/$activitySlug/',
    path: '/activite/$activitySlug/',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicActiviteActivitySlugProductSlugRoute =
  PublicActiviteActivitySlugProductSlugRouteImport.update({
    id: '/activite/$activitySlug/$productSlug',
    path: '/activite/$activitySlug/$productSlug',
    getParentRoute: () => PublicRoute,
  } as any)
const AdminLayoutEquipeIndexRoute = AdminLayoutEquipeIndexRouteImport.update({
  id: '/equipe/',
  path: '/equipe/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutEquipementsIndexRoute =
  AdminLayoutEquipementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutEquipementsRoute,
  } as any)
const AdminLayoutEquipementsItemIdRoute =
  AdminLayoutEquipementsItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AdminLayoutEquipementsRoute,
  } as any)
const AdminLayoutEquipementsAjouterRoute =
  AdminLayoutEquipementsAjouterRouteImport.update({
    id: '/ajouter',
    path: '/ajouter',
    getParentRoute: () => AdminLayoutEquipementsRoute,
  } as any)
const AdminLayoutReglagesIndexRoute =
  AdminLayoutReglagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutReglagesRoute,
  } as any)
const AdminLayoutReglagesCategoriesRoute =
  AdminLayoutReglagesCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminLayoutReglagesRoute,
  } as any)
const AdminLayoutReglagesFacturationRoute =
  AdminLayoutReglagesFacturationRouteImport.update({
    id: '/facturation',
    path: '/facturation',
    getParentRoute: () => AdminLayoutReglagesRoute,
  } as any)
const AdminLayoutReglagesHorairesRoute =
  AdminLayoutReglagesHorairesRouteImport.update({
    id: '/horaires',
    path: '/horaires',
    getParentRoute: () => AdminLayoutReglagesRoute,
  } as any)
const AdminLayoutReglagesProduitsRoute =
  AdminLayoutReglagesProduitsRouteImport.update({
    id: '/produits',
    path: '/produits',
    getParentRoute: () => AdminLayoutReglagesRoute,
  } as any)
const AdminLayoutReservationsIndexRoute =
  AdminLayoutReservationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutReservationsRoute,
  } as any)
const AdminLayoutReservationsReservationIdRoute =
  AdminLayoutReservationsReservationIdRouteImport.update({
    id: '/$reservationId',
    path: '/$reservationId',
    getParentRoute: () => AdminLayoutReservationsRoute,
  } as any)
const AdminLayoutReservationsAjouterRoute =
  AdminLayoutReservationsAjouterRouteImport.update({
    id: '/ajouter',
    path: '/ajouter',
    getParentRoute: () => AdminLayoutReservationsRoute,
  } as any)
const AdminLayoutUtilisateursIndexRoute =
  AdminLayoutUtilisateursIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutUtilisateursRoute,
  } as any)
const AdminLayoutUtilisateursUserIdRoute =
  AdminLayoutUtilisateursUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AdminLayoutUtilisateursRoute,
  } as any)
const AdminLayoutUtilisateursAjouterRoute =
  AdminLayoutUtilisateursAjouterRouteImport.update({
    id: '/ajouter',
    path: '/ajouter',
    getParentRoute: () => AdminLayoutUtilisateursRoute,
  } as any)
const AdminLayoutEquipementsItemIdIndexRoute =
  AdminLayoutEquipementsItemIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutEquipementsItemIdRoute,
  } as any)
const AdminLayoutEquipementsItemIdModifierRoute =
  AdminLayoutEquipementsItemIdModifierRouteImport.update({
    id: '/modifier',
    path: '/modifier',
    getParentRoute: () => AdminLayoutEquipementsItemIdRoute,
  } as any)
const AdminLayoutReservationsReservationIdIndexRoute =
  AdminLayoutReservationsReservationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutReservationsReservationIdRoute,
  } as any)
const AdminLayoutUtilisateursUserIdIndexRoute =
  AdminLayoutUtilisateursUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutUtilisateursUserIdRoute,
  } as any)
const AdminLayoutUtilisateursUserIdModifierRoute =
  AdminLayoutUtilisateursUserIdModifierRouteImport.update({
    id: '/modifier',
    path: '/modifier',
    getParentRoute: () => AdminLayoutUtilisateursUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof PublicConnexionRoute
  '/location-materiel-{$ville}': typeof PublicLocationMaterielChar123villeChar125Route
  '/mon-compte': typeof PublicMonCompteRoute
  '/panier': typeof PublicPanierRoute
  '/reservation': typeof PublicReservationRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/mot-de-passe-oublie': typeof AdminMotDePasseOublieRoute
  '/admin/reinitialiser-mot-de-passe': typeof AdminReinitialiserMotDePasseRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/reservation/$reference': typeof PublicReservationReferenceRoute
  '/admin/compte': typeof AdminLayoutCompteRoute
  '/admin/durees': typeof AdminLayoutDureesRoute
  '/admin/equipements': typeof AdminLayoutEquipementsRouteWithChildren
  '/admin/facturation': typeof AdminLayoutFacturationRoute
  '/admin/reglages': typeof AdminLayoutReglagesRouteWithChildren
  '/admin/reservations': typeof AdminLayoutReservationsRouteWithChildren
  '/admin/statistiques': typeof AdminLayoutStatistiquesRoute
  '/admin/utilisateurs': typeof AdminLayoutUtilisateursRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/activite/$activitySlug/$productSlug': typeof PublicActiviteActivitySlugProductSlugRoute
  '/admin/equipements/$itemId': typeof AdminLayoutEquipementsItemIdRouteWithChildren
  '/admin/equipements/ajouter': typeof AdminLayoutEquipementsAjouterRoute
  '/admin/reglages/categories': typeof AdminLayoutReglagesCategoriesRoute
  '/admin/reglages/facturation': typeof AdminLayoutReglagesFacturationRoute
  '/admin/reglages/horaires': typeof AdminLayoutReglagesHorairesRoute
  '/admin/reglages/produits': typeof AdminLayoutReglagesProduitsRoute
  '/admin/reservations/$reservationId': typeof AdminLayoutReservationsReservationIdRouteWithChildren
  '/admin/reservations/ajouter': typeof AdminLayoutReservationsAjouterRoute
  '/admin/utilisateurs/$userId': typeof AdminLayoutUtilisateursUserIdRouteWithChildren
  '/admin/utilisateurs/ajouter': typeof AdminLayoutUtilisateursAjouterRoute
  '/activite/$activitySlug/': typeof PublicActiviteActivitySlugIndexRoute
  '/admin/equipe/': typeof AdminLayoutEquipeIndexRoute
  '/admin/equipements/': typeof AdminLayoutEquipementsIndexRoute
  '/admin/reglages/': typeof AdminLayoutReglagesIndexRoute
  '/admin/reservations/': typeof AdminLayoutReservationsIndexRoute
  '/admin/utilisateurs/': typeof AdminLayoutUtilisateursIndexRoute
  '/admin/equipements/$itemId/modifier': typeof AdminLayoutEquipementsItemIdModifierRoute
  '/admin/utilisateurs/$userId/modifier': typeof AdminLayoutUtilisateursUserIdModifierRoute
  '/admin/equipements/$itemId/': typeof AdminLayoutEquipementsItemIdIndexRoute
  '/admin/reservations/$reservationId/': typeof AdminLayoutReservationsReservationIdIndexRoute
  '/admin/utilisateurs/$userId/': typeof AdminLayoutUtilisateursUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof PublicConnexionRoute
  '/location-materiel-{$ville}': typeof PublicLocationMaterielChar123villeChar125Route
  '/mon-compte': typeof PublicMonCompteRoute
  '/panier': typeof PublicPanierRoute
  '/reservation': typeof PublicReservationRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/mot-de-passe-oublie': typeof AdminMotDePasseOublieRoute
  '/admin/reinitialiser-mot-de-passe': typeof AdminReinitialiserMotDePasseRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/reservation/$reference': typeof PublicReservationReferenceRoute
  '/admin/compte': typeof AdminLayoutCompteRoute
  '/admin/durees': typeof AdminLayoutDureesRoute
  '/admin/facturation': typeof AdminLayoutFacturationRoute
  '/admin/statistiques': typeof AdminLayoutStatistiquesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/activite/$activitySlug/$productSlug': typeof PublicActiviteActivitySlugProductSlugRoute
  '/admin/equipements/ajouter': typeof AdminLayoutEquipementsAjouterRoute
  '/admin/reglages/categories': typeof AdminLayoutReglagesCategoriesRoute
  '/admin/reglages/facturation': typeof AdminLayoutReglagesFacturationRoute
  '/admin/reglages/horaires': typeof AdminLayoutReglagesHorairesRoute
  '/admin/reglages/produits': typeof AdminLayoutReglagesProduitsRoute
  '/admin/reservations/ajouter': typeof AdminLayoutReservationsAjouterRoute
  '/admin/utilisateurs/ajouter': typeof AdminLayoutUtilisateursAjouterRoute
  '/activite/$activitySlug': typeof PublicActiviteActivitySlugIndexRoute
  '/admin/equipe': typeof AdminLayoutEquipeIndexRoute
  '/admin/equipements': typeof AdminLayoutEquipementsIndexRoute
  '/admin/reglages': typeof AdminLayoutReglagesIndexRoute
  '/admin/reservations': typeof AdminLayoutReservationsIndexRoute
  '/admin/utilisateurs': typeof AdminLayoutUtilisateursIndexRoute
  '/admin/equipements/$itemId/modifier': typeof AdminLayoutEquipementsItemIdModifierRoute
  '/admin/utilisateurs/$userId/modifier': typeof AdminLayoutUtilisateursUserIdModifierRoute
  '/admin/equipements/$itemId': typeof AdminLayoutEquipementsItemIdIndexRoute
  '/admin/reservations/$reservationId': typeof AdminLayoutReservationsReservationIdIndexRoute
  '/admin/utilisateurs/$userId': typeof AdminLayoutUtilisateursUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/_public/connexion': typeof PublicConnexionRoute
  '/_public/location-materiel-{$ville}': typeof PublicLocationMaterielChar123villeChar125Route
  '/_public/mon-compte': typeof PublicMonCompteRoute
  '/_public/panier': typeof PublicPanierRoute
  '/_public/reservation': typeof PublicReservationRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/mot-de-passe-oublie': typeof AdminMotDePasseOublieRoute
  '/admin/reinitialiser-mot-de-passe': typeof AdminReinitialiserMotDePasseRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/_public/reservation/$reference': typeof PublicReservationReferenceRoute
  '/admin/_layout/compte': typeof AdminLayoutCompteRoute
  '/admin/_layout/durees': typeof AdminLayoutDureesRoute
  '/admin/_layout/equipements': typeof AdminLayoutEquipementsRouteWithChildren
  '/admin/_layout/facturation': typeof AdminLayoutFacturationRoute
  '/admin/_layout/reglages': typeof AdminLayoutReglagesRouteWithChildren
  '/admin/_layout/reservations': typeof AdminLayoutReservationsRouteWithChildren
  '/admin/_layout/statistiques': typeof AdminLayoutStatistiquesRoute
  '/admin/_layout/utilisateurs': typeof AdminLayoutUtilisateursRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/_public/activite/$activitySlug/$productSlug': typeof PublicActiviteActivitySlugProductSlugRoute
  '/admin/_layout/equipements/$itemId': typeof AdminLayoutEquipementsItemIdRouteWithChildren
  '/admin/_layout/equipements/ajouter': typeof AdminLayoutEquipementsAjouterRoute
  '/admin/_layout/reglages/categories': typeof AdminLayoutReglagesCategoriesRoute
  '/admin/_layout/reglages/facturation': typeof AdminLayoutReglagesFacturationRoute
  '/admin/_layout/reglages/horaires': typeof AdminLayoutReglagesHorairesRoute
  '/admin/_layout/reglages/produits': typeof AdminLayoutReglagesProduitsRoute
  '/admin/_layout/reservations/$reservationId': typeof AdminLayoutReservationsReservationIdRouteWithChildren
  '/admin/_layout/reservations/ajouter': typeof AdminLayoutReservationsAjouterRoute
  '/admin/_layout/utilisateurs/$userId': typeof AdminLayoutUtilisateursUserIdRouteWithChildren
  '/admin/_layout/utilisateurs/ajouter': typeof AdminLayoutUtilisateursAjouterRoute
  '/_public/activite/$activitySlug/': typeof PublicActiviteActivitySlugIndexRoute
  '/admin/_layout/equipe/': typeof AdminLayoutEquipeIndexRoute
  '/admin/_layout/equipements/': typeof AdminLayoutEquipementsIndexRoute
  '/admin/_layout/reglages/': typeof AdminLayoutReglagesIndexRoute
  '/admin/_layout/reservations/': typeof AdminLayoutReservationsIndexRoute
  '/admin/_layout/utilisateurs/': typeof AdminLayoutUtilisateursIndexRoute
  '/admin/_layout/equipements/$itemId/modifier': typeof AdminLayoutEquipementsItemIdModifierRoute
  '/admin/_layout/utilisateurs/$userId/modifier': typeof AdminLayoutUtilisateursUserIdModifierRoute
  '/admin/_layout/equipements/$itemId/': typeof AdminLayoutEquipementsItemIdIndexRoute
  '/admin/_layout/reservations/$reservationId/': typeof AdminLayoutReservationsReservationIdIndexRoute
  '/admin/_layout/utilisateurs/$userId/': typeof AdminLayoutUtilisateursUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/location-materiel-{$ville}'
    | '/mon-compte'
    | '/panier'
    | '/reservation'
    | '/admin'
    | '/admin/login'
    | '/admin/mot-de-passe-oublie'
    | '/admin/reinitialiser-mot-de-passe'
    | '/api/sitemap'
    | '/reservation/$reference'
    | '/admin/compte'
    | '/admin/durees'
    | '/admin/equipements'
    | '/admin/facturation'
    | '/admin/reglages'
    | '/admin/reservations'
    | '/admin/statistiques'
    | '/admin/utilisateurs'
    | '/api/auth/$'
    | '/admin/'
    | '/activite/$activitySlug/$productSlug'
    | '/admin/equipements/$itemId'
    | '/admin/equipements/ajouter'
    | '/admin/reglages/categories'
    | '/admin/reglages/facturation'
    | '/admin/reglages/horaires'
    | '/admin/reglages/produits'
    | '/admin/reservations/$reservationId'
    | '/admin/reservations/ajouter'
    | '/admin/utilisateurs/$userId'
    | '/admin/utilisateurs/ajouter'
    | '/activite/$activitySlug/'
    | '/admin/equipe/'
    | '/admin/equipements/'
    | '/admin/reglages/'
    | '/admin/reservations/'
    | '/admin/utilisateurs/'
    | '/admin/equipements/$itemId/modifier'
    | '/admin/utilisateurs/$userId/modifier'
    | '/admin/equipements/$itemId/'
    | '/admin/reservations/$reservationId/'
    | '/admin/utilisateurs/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/location-materiel-{$ville}'
    | '/mon-compte'
    | '/panier'
    | '/reservation'
    | '/admin/login'
    | '/admin/mot-de-passe-oublie'
    | '/admin/reinitialiser-mot-de-passe'
    | '/api/sitemap'
    | '/reservation/$reference'
    | '/admin/compte'
    | '/admin/durees'
    | '/admin/facturation'
    | '/admin/statistiques'
    | '/api/auth/$'
    | '/admin'
    | '/activite/$activitySlug/$productSlug'
    | '/admin/equipements/ajouter'
    | '/admin/reglages/categories'
    | '/admin/reglages/facturation'
    | '/admin/reglages/horaires'
    | '/admin/reglages/produits'
    | '/admin/reservations/ajouter'
    | '/admin/utilisateurs/ajouter'
    | '/activite/$activitySlug'
    | '/admin/equipe'
    | '/admin/equipements'
    | '/admin/reglages'
    | '/admin/reservations'
    | '/admin/utilisateurs'
    | '/admin/equipements/$itemId/modifier'
    | '/admin/utilisateurs/$userId/modifier'
    | '/admin/equipements/$itemId'
    | '/admin/reservations/$reservationId'
    | '/admin/utilisateurs/$userId'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/_public/connexion'
    | '/_public/location-materiel-{$ville}'
    | '/_public/mon-compte'
    | '/_public/panier'
    | '/_public/reservation'
    | '/admin/_layout'
    | '/admin/login'
    | '/admin/mot-de-passe-oublie'
    | '/admin/reinitialiser-mot-de-passe'
    | '/api/sitemap'
    | '/_public/reservation/$reference'
    | '/admin/_layout/compte'
    | '/admin/_layout/durees'
    | '/admin/_layout/equipements'
    | '/admin/_layout/facturation'
    | '/admin/_layout/reglages'
    | '/admin/_layout/reservations'
    | '/admin/_layout/statistiques'
    | '/admin/_layout/utilisateurs'
    | '/api/auth/$'
    | '/admin/_layout/'
    | '/_public/activite/$activitySlug/$productSlug'
    | '/admin/_layout/equipements/$itemId'
    | '/admin/_layout/equipements/ajouter'
    | '/admin/_layout/reglages/categories'
    | '/admin/_layout/reglages/facturation'
    | '/admin/_layout/reglages/horaires'
    | '/admin/_layout/reglages/produits'
    | '/admin/_layout/reservations/$reservationId'
    | '/admin/_layout/reservations/ajouter'
    | '/admin/_layout/utilisateurs/$userId'
    | '/admin/_layout/utilisateurs/ajouter'
    | '/_public/activite/$activitySlug/'
    | '/admin/_layout/equipe/'
    | '/admin/_layout/equipements/'
    | '/admin/_layout/reglages/'
    | '/admin/_layout/reservations/'
    | '/admin/_layout/utilisateurs/'
    | '/admin/_layout/equipements/$itemId/modifier'
    | '/admin/_layout/utilisateurs/$userId/modifier'
    | '/admin/_layout/equipements/$itemId/'
    | '/admin/_layout/reservations/$reservationId/'
    | '/admin/_layout/utilisateurs/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMotDePasseOublieRoute: typeof AdminMotDePasseOublieRoute
  AdminReinitialiserMotDePasseRoute: typeof AdminReinitialiserMotDePasseRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/connexion': {
      id: '/_public/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof PublicConnexionRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/location-materiel-{$ville}': {
      id: '/_public/location-materiel-{$ville}'
      path: '/location-materiel-{$ville}'
      fullPath: '/location-materiel-{$ville}'
      preLoaderRoute: typeof PublicLocationMaterielChar123villeChar125RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mon-compte': {
      id: '/_public/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof PublicMonCompteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/panier': {
      id: '/_public/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PublicPanierRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reservation': {
      id: '/_public/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof PublicReservationRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mot-de-passe-oublie': {
      id: '/admin/mot-de-passe-oublie'
      path: '/admin/mot-de-passe-oublie'
      fullPath: '/admin/mot-de-passe-oublie'
      preLoaderRoute: typeof AdminMotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reinitialiser-mot-de-passe': {
      id: '/admin/reinitialiser-mot-de-passe'
      path: '/admin/reinitialiser-mot-de-passe'
      fullPath: '/admin/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof AdminReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/reservation/$reference': {
      id: '/_public/reservation/$reference'
      path: '/$reference'
      fullPath: '/reservation/$reference'
      preLoaderRoute: typeof PublicReservationReferenceRouteImport
      parentRoute: typeof PublicReservationRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/compte': {
      id: '/admin/_layout/compte'
      path: '/compte'
      fullPath: '/admin/compte'
      preLoaderRoute: typeof AdminLayoutCompteRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/durees': {
      id: '/admin/_layout/durees'
      path: '/durees'
      fullPath: '/admin/durees'
      preLoaderRoute: typeof AdminLayoutDureesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/equipements': {
      id: '/admin/_layout/equipements'
      path: '/equipements'
      fullPath: '/admin/equipements'
      preLoaderRoute: typeof AdminLayoutEquipementsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/facturation': {
      id: '/admin/_layout/facturation'
      path: '/facturation'
      fullPath: '/admin/facturation'
      preLoaderRoute: typeof AdminLayoutFacturationRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reglages': {
      id: '/admin/_layout/reglages'
      path: '/reglages'
      fullPath: '/admin/reglages'
      preLoaderRoute: typeof AdminLayoutReglagesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reservations': {
      id: '/admin/_layout/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminLayoutReservationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/statistiques': {
      id: '/admin/_layout/statistiques'
      path: '/statistiques'
      fullPath: '/admin/statistiques'
      preLoaderRoute: typeof AdminLayoutStatistiquesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/utilisateurs': {
      id: '/admin/_layout/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminLayoutUtilisateursRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/activite/$activitySlug/': {
      id: '/_public/activite/$activitySlug/'
      path: '/activite/$activitySlug'
      fullPath: '/activite/$activitySlug/'
      preLoaderRoute: typeof PublicActiviteActivitySlugIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/activite/$activitySlug/$productSlug': {
      id: '/_public/activite/$activitySlug/$productSlug'
      path: '/activite/$activitySlug/$productSlug'
      fullPath: '/activite/$activitySlug/$productSlug'
      preLoaderRoute: typeof PublicActiviteActivitySlugProductSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/_layout/equipe/': {
      id: '/admin/_layout/equipe/'
      path: '/equipe'
      fullPath: '/admin/equipe/'
      preLoaderRoute: typeof AdminLayoutEquipeIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/equipements/': {
      id: '/admin/_layout/equipements/'
      path: '/'
      fullPath: '/admin/equipements/'
      preLoaderRoute: typeof AdminLayoutEquipementsIndexRouteImport
      parentRoute: typeof AdminLayoutEquipementsRoute
    }
    '/admin/_layout/equipements/$itemId': {
      id: '/admin/_layout/equipements/$itemId'
      path: '/$itemId'
      fullPath: '/admin/equipements/$itemId'
      preLoaderRoute: typeof AdminLayoutEquipementsItemIdRouteImport
      parentRoute: typeof AdminLayoutEquipementsRoute
    }
    '/admin/_layout/equipements/ajouter': {
      id: '/admin/_layout/equipements/ajouter'
      path: '/ajouter'
      fullPath: '/admin/equipements/ajouter'
      preLoaderRoute: typeof AdminLayoutEquipementsAjouterRouteImport
      parentRoute: typeof AdminLayoutEquipementsRoute
    }
    '/admin/_layout/reglages/': {
      id: '/admin/_layout/reglages/'
      path: '/'
      fullPath: '/admin/reglages/'
      preLoaderRoute: typeof AdminLayoutReglagesIndexRouteImport
      parentRoute: typeof AdminLayoutReglagesRoute
    }
    '/admin/_layout/reglages/categories': {
      id: '/admin/_layout/reglages/categories'
      path: '/categories'
      fullPath: '/admin/reglages/categories'
      preLoaderRoute: typeof AdminLayoutReglagesCategoriesRouteImport
      parentRoute: typeof AdminLayoutReglagesRoute
    }
    '/admin/_layout/reglages/facturation': {
      id: '/admin/_layout/reglages/facturation'
      path: '/facturation'
      fullPath: '/admin/reglages/facturation'
      preLoaderRoute: typeof AdminLayoutReglagesFacturationRouteImport
      parentRoute: typeof AdminLayoutReglagesRoute
    }
    '/admin/_layout/reglages/horaires': {
      id: '/admin/_layout/reglages/horaires'
      path: '/horaires'
      fullPath: '/admin/reglages/horaires'
      preLoaderRoute: typeof AdminLayoutReglagesHorairesRouteImport
      parentRoute: typeof AdminLayoutReglagesRoute
    }
    '/admin/_layout/reglages/produits': {
      id: '/admin/_layout/reglages/produits'
      path: '/produits'
      fullPath: '/admin/reglages/produits'
      preLoaderRoute: typeof AdminLayoutReglagesProduitsRouteImport
      parentRoute: typeof AdminLayoutReglagesRoute
    }
    '/admin/_layout/reservations/': {
      id: '/admin/_layout/reservations/'
      path: '/'
      fullPath: '/admin/reservations/'
      preLoaderRoute: typeof AdminLayoutReservationsIndexRouteImport
      parentRoute: typeof AdminLayoutReservationsRoute
    }
    '/admin/_layout/reservations/$reservationId': {
      id: '/admin/_layout/reservations/$reservationId'
      path: '/$reservationId'
      fullPath: '/admin/reservations/$reservationId'
      preLoaderRoute: typeof AdminLayoutReservationsReservationIdRouteImport
      parentRoute: typeof AdminLayoutReservationsRoute
    }
    '/admin/_layout/reservations/ajouter': {
      id: '/admin/_layout/reservations/ajouter'
      path: '/ajouter'
      fullPath: '/admin/reservations/ajouter'
      preLoaderRoute: typeof AdminLayoutReservationsAjouterRouteImport
      parentRoute: typeof AdminLayoutReservationsRoute
    }
    '/admin/_layout/utilisateurs/': {
      id: '/admin/_layout/utilisateurs/'
      path: '/'
      fullPath: '/admin/utilisateurs/'
      preLoaderRoute: typeof AdminLayoutUtilisateursIndexRouteImport
      parentRoute: typeof AdminLayoutUtilisateursRoute
    }
    '/admin/_layout/utilisateurs/$userId': {
      id: '/admin/_layout/utilisateurs/$userId'
      path: '/$userId'
      fullPath: '/admin/utilisateurs/$userId'
      preLoaderRoute: typeof AdminLayoutUtilisateursUserIdRouteImport
      parentRoute: typeof AdminLayoutUtilisateursRoute
    }
    '/admin/_layout/utilisateurs/ajouter': {
      id: '/admin/_layout/utilisateurs/ajouter'
      path: '/ajouter'
      fullPath: '/admin/utilisateurs/ajouter'
      preLoaderRoute: typeof AdminLayoutUtilisateursAjouterRouteImport
      parentRoute: typeof AdminLayoutUtilisateursRoute
    }
    '/admin/_layout/equipements/$itemId/': {
      id: '/admin/_layout/equipements/$itemId/'
      path: '/'
      fullPath: '/admin/equipements/$itemId/'
      preLoaderRoute: typeof AdminLayoutEquipementsItemIdIndexRouteImport
      parentRoute: typeof AdminLayoutEquipementsItemIdRoute
    }
    '/admin/_layout/equipements/$itemId/modifier': {
      id: '/admin/_layout/equipements/$itemId/modifier'
      path: '/modifier'
      fullPath: '/admin/equipements/$itemId/modifier'
      preLoaderRoute: typeof AdminLayoutEquipementsItemIdModifierRouteImport
      parentRoute: typeof AdminLayoutEquipementsItemIdRoute
    }
    '/admin/_layout/reservations/$reservationId/': {
      id: '/admin/_layout/reservations/$reservationId/'
      path: '/'
      fullPath: '/admin/reservations/$reservationId/'
      preLoaderRoute: typeof AdminLayoutReservationsReservationIdIndexRouteImport
      parentRoute: typeof AdminLayoutReservationsReservationIdRoute
    }
    '/admin/_layout/utilisateurs/$userId/': {
      id: '/admin/_layout/utilisateurs/$userId/'
      path: '/'
      fullPath: '/admin/utilisateurs/$userId/'
      preLoaderRoute: typeof AdminLayoutUtilisateursUserIdIndexRouteImport
      parentRoute: typeof AdminLayoutUtilisateursUserIdRoute
    }
    '/admin/_layout/utilisateurs/$userId/modifier': {
      id: '/admin/_layout/utilisateurs/$userId/modifier'
      path: '/modifier'
      fullPath: '/admin/utilisateurs/$userId/modifier'
      preLoaderRoute: typeof AdminLayoutUtilisateursUserIdModifierRouteImport
      parentRoute: typeof AdminLayoutUtilisateursUserIdRoute
    }
  }
}

interface PublicReservationRouteChildren {
  PublicReservationReferenceRoute: typeof PublicReservationReferenceRoute
}

const PublicReservationRouteChildren: PublicReservationRouteChildren = {
  PublicReservationReferenceRoute: PublicReservationReferenceRoute,
}

const PublicReservationRouteWithChildren =
  PublicReservationRoute._addFileChildren(PublicReservationRouteChildren)

interface PublicRouteChildren {
  PublicConnexionRoute: typeof PublicConnexionRoute
  PublicLocationMaterielChar123villeChar125Route: typeof PublicLocationMaterielChar123villeChar125Route
  PublicMonCompteRoute: typeof PublicMonCompteRoute
  PublicPanierRoute: typeof PublicPanierRoute
  PublicReservationRoute: typeof PublicReservationRouteWithChildren
  PublicActiviteActivitySlugProductSlugRoute: typeof PublicActiviteActivitySlugProductSlugRoute
  PublicActiviteActivitySlugIndexRoute: typeof PublicActiviteActivitySlugIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicConnexionRoute: PublicConnexionRoute,
  PublicLocationMaterielChar123villeChar125Route:
    PublicLocationMaterielChar123villeChar125Route,
  PublicMonCompteRoute: PublicMonCompteRoute,
  PublicPanierRoute: PublicPanierRoute,
  PublicReservationRoute: PublicReservationRouteWithChildren,
  PublicActiviteActivitySlugProductSlugRoute:
    PublicActiviteActivitySlugProductSlugRoute,
  PublicActiviteActivitySlugIndexRoute: PublicActiviteActivitySlugIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminLayoutEquipementsItemIdRouteChildren {
  AdminLayoutEquipementsItemIdModifierRoute: typeof AdminLayoutEquipementsItemIdModifierRoute
  AdminLayoutEquipementsItemIdIndexRoute: typeof AdminLayoutEquipementsItemIdIndexRoute
}

const AdminLayoutEquipementsItemIdRouteChildren: AdminLayoutEquipementsItemIdRouteChildren =
  {
    AdminLayoutEquipementsItemIdModifierRoute:
      AdminLayoutEquipementsItemIdModifierRoute,
    AdminLayoutEquipementsItemIdIndexRoute:
      AdminLayoutEquipementsItemIdIndexRoute,
  }

const AdminLayoutEquipementsItemIdRouteWithChildren =
  AdminLayoutEquipementsItemIdRoute._addFileChildren(
    AdminLayoutEquipementsItemIdRouteChildren,
  )

interface AdminLayoutEquipementsRouteChildren {
  AdminLayoutEquipementsItemIdRoute: typeof AdminLayoutEquipementsItemIdRouteWithChildren
  AdminLayoutEquipementsAjouterRoute: typeof AdminLayoutEquipementsAjouterRoute
  AdminLayoutEquipementsIndexRoute: typeof AdminLayoutEquipementsIndexRoute
}

const AdminLayoutEquipementsRouteChildren: AdminLayoutEquipementsRouteChildren =
  {
    AdminLayoutEquipementsItemIdRoute:
      AdminLayoutEquipementsItemIdRouteWithChildren,
    AdminLayoutEquipementsAjouterRoute: AdminLayoutEquipementsAjouterRoute,
    AdminLayoutEquipementsIndexRoute: AdminLayoutEquipementsIndexRoute,
  }

const AdminLayoutEquipementsRouteWithChildren =
  AdminLayoutEquipementsRoute._addFileChildren(
    AdminLayoutEquipementsRouteChildren,
  )

interface AdminLayoutReglagesRouteChildren {
  AdminLayoutReglagesCategoriesRoute: typeof AdminLayoutReglagesCategoriesRoute
  AdminLayoutReglagesFacturationRoute: typeof AdminLayoutReglagesFacturationRoute
  AdminLayoutReglagesHorairesRoute: typeof AdminLayoutReglagesHorairesRoute
  AdminLayoutReglagesProduitsRoute: typeof AdminLayoutReglagesProduitsRoute
  AdminLayoutReglagesIndexRoute: typeof AdminLayoutReglagesIndexRoute
}

const AdminLayoutReglagesRouteChildren: AdminLayoutReglagesRouteChildren = {
  AdminLayoutReglagesCategoriesRoute: AdminLayoutReglagesCategoriesRoute,
  AdminLayoutReglagesFacturationRoute: AdminLayoutReglagesFacturationRoute,
  AdminLayoutReglagesHorairesRoute: AdminLayoutReglagesHorairesRoute,
  AdminLayoutReglagesProduitsRoute: AdminLayoutReglagesProduitsRoute,
  AdminLayoutReglagesIndexRoute: AdminLayoutReglagesIndexRoute,
}

const AdminLayoutReglagesRouteWithChildren =
  AdminLayoutReglagesRoute._addFileChildren(AdminLayoutReglagesRouteChildren)

interface AdminLayoutReservationsReservationIdRouteChildren {
  AdminLayoutReservationsReservationIdIndexRoute: typeof AdminLayoutReservationsReservationIdIndexRoute
}

const AdminLayoutReservationsReservationIdRouteChildren: AdminLayoutReservationsReservationIdRouteChildren =
  {
    AdminLayoutReservationsReservationIdIndexRoute:
      AdminLayoutReservationsReservationIdIndexRoute,
  }

const AdminLayoutReservationsReservationIdRouteWithChildren =
  AdminLayoutReservationsReservationIdRoute._addFileChildren(
    AdminLayoutReservationsReservationIdRouteChildren,
  )

interface AdminLayoutReservationsRouteChildren {
  AdminLayoutReservationsReservationIdRoute: typeof AdminLayoutReservationsReservationIdRouteWithChildren
  AdminLayoutReservationsAjouterRoute: typeof AdminLayoutReservationsAjouterRoute
  AdminLayoutReservationsIndexRoute: typeof AdminLayoutReservationsIndexRoute
}

const AdminLayoutReservationsRouteChildren: AdminLayoutReservationsRouteChildren =
  {
    AdminLayoutReservationsReservationIdRoute:
      AdminLayoutReservationsReservationIdRouteWithChildren,
    AdminLayoutReservationsAjouterRoute: AdminLayoutReservationsAjouterRoute,
    AdminLayoutReservationsIndexRoute: AdminLayoutReservationsIndexRoute,
  }

const AdminLayoutReservationsRouteWithChildren =
  AdminLayoutReservationsRoute._addFileChildren(
    AdminLayoutReservationsRouteChildren,
  )

interface AdminLayoutUtilisateursUserIdRouteChildren {
  AdminLayoutUtilisateursUserIdModifierRoute: typeof AdminLayoutUtilisateursUserIdModifierRoute
  AdminLayoutUtilisateursUserIdIndexRoute: typeof AdminLayoutUtilisateursUserIdIndexRoute
}

const AdminLayoutUtilisateursUserIdRouteChildren: AdminLayoutUtilisateursUserIdRouteChildren =
  {
    AdminLayoutUtilisateursUserIdModifierRoute:
      AdminLayoutUtilisateursUserIdModifierRoute,
    AdminLayoutUtilisateursUserIdIndexRoute:
      AdminLayoutUtilisateursUserIdIndexRoute,
  }

const AdminLayoutUtilisateursUserIdRouteWithChildren =
  AdminLayoutUtilisateursUserIdRoute._addFileChildren(
    AdminLayoutUtilisateursUserIdRouteChildren,
  )

interface AdminLayoutUtilisateursRouteChildren {
  AdminLayoutUtilisateursUserIdRoute: typeof AdminLayoutUtilisateursUserIdRouteWithChildren
  AdminLayoutUtilisateursAjouterRoute: typeof AdminLayoutUtilisateursAjouterRoute
  AdminLayoutUtilisateursIndexRoute: typeof AdminLayoutUtilisateursIndexRoute
}

const AdminLayoutUtilisateursRouteChildren: AdminLayoutUtilisateursRouteChildren =
  {
    AdminLayoutUtilisateursUserIdRoute:
      AdminLayoutUtilisateursUserIdRouteWithChildren,
    AdminLayoutUtilisateursAjouterRoute: AdminLayoutUtilisateursAjouterRoute,
    AdminLayoutUtilisateursIndexRoute: AdminLayoutUtilisateursIndexRoute,
  }

const AdminLayoutUtilisateursRouteWithChildren =
  AdminLayoutUtilisateursRoute._addFileChildren(
    AdminLayoutUtilisateursRouteChildren,
  )

interface AdminLayoutRouteChildren {
  AdminLayoutCompteRoute: typeof AdminLayoutCompteRoute
  AdminLayoutDureesRoute: typeof AdminLayoutDureesRoute
  AdminLayoutEquipementsRoute: typeof AdminLayoutEquipementsRouteWithChildren
  AdminLayoutFacturationRoute: typeof AdminLayoutFacturationRoute
  AdminLayoutReglagesRoute: typeof AdminLayoutReglagesRouteWithChildren
  AdminLayoutReservationsRoute: typeof AdminLayoutReservationsRouteWithChildren
  AdminLayoutStatistiquesRoute: typeof AdminLayoutStatistiquesRoute
  AdminLayoutUtilisateursRoute: typeof AdminLayoutUtilisateursRouteWithChildren
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutEquipeIndexRoute: typeof AdminLayoutEquipeIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutCompteRoute: AdminLayoutCompteRoute,
  AdminLayoutDureesRoute: AdminLayoutDureesRoute,
  AdminLayoutEquipementsRoute: AdminLayoutEquipementsRouteWithChildren,
  AdminLayoutFacturationRoute: AdminLayoutFacturationRoute,
  AdminLayoutReglagesRoute: AdminLayoutReglagesRouteWithChildren,
  AdminLayoutReservationsRoute: AdminLayoutReservationsRouteWithChildren,
  AdminLayoutStatistiquesRoute: AdminLayoutStatistiquesRoute,
  AdminLayoutUtilisateursRoute: AdminLayoutUtilisateursRouteWithChildren,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutEquipeIndexRoute: AdminLayoutEquipeIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMotDePasseOublieRoute: AdminMotDePasseOublieRoute,
  AdminReinitialiserMotDePasseRoute: AdminReinitialiserMotDePasseRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
